### ISSUE TITLE
TODO: Add tests! 

### ISSUE THREAD

**Issue by mithi** [mithi/bare-minimum-2d#12]
# Use jest 😃 
https://jestjs.io/

## Example of snapshot testing
https://jestjs.io/docs/en/snapshot-testing
another test example: https://github.com/mithi/bare-minimum-3d/tree/master/test

# This is the sample input
https://github.com/mithi/bare-minimum-2d/blob/master/example/src/demo1/demoProps.js

# And this is the corresponding svg output
https://github.com/mithi/bare-minimum-2d/blob/master/example/src/demo1/demo.svg

**Comment by Ruchika30** [comment]
Would like to work on this @mithi
