### ISSUE TITLE
Markers with a text label

### ISSUE THREAD

**Issue by fuddl** [mithi/bare-minimum-2d#27]
Hi,

I'd like to append text labels to each marker:
 
![nearby stars](https://user-images.githubusercontent.com/842548/111220604-ae15e500-85d9-11eb-83aa-50733b0be7a7.gif)

these should also make sure not to overlap with other text markers.

please let me know if this exceeds the boundaries of _bare minimum_ 😅.

Would It be possible to define a marker type as a plug-in? such a plug-in could be used to solve #1

**Comment by mithi** [comment]
@fuddl 
Sorry for the late reply.

Oh my god, this is so so cool!

What algorithm did you use to determine whether the points are overlapping? Did you just sort 
the z-points of each point? That's awesome. Unfortunately it wouldn't work with lines and polygons though :/

My recommendation is that you write a package given this functionality (if you feel inclined)
and just list `bare minimum 2d` and `bare minimum 3d ` as  peer dependencies in your `package.json`
 (I guess it's a plugin ?)


If you do, I'll put it a link right before the `demo application` of my READMEs, to make sure everyone who visits the `bare minimum 2d` repo and `bare minimum will know about it!

Let me know your thoughts. Thanks!

**Comment by fuddl** [comment]
> What algorithm did you use to determine whether the points are overlapping? Did you just sort
> the z-points of each point?

currently I go by render order: the element which is rendered first (in the DOM), takes priority. I could probably prioritise whatever is closer to the camera. But the first approach works better for me.

> My recommendation is that you write a package given this functionality (if you feel inclined)
> and just list `bare minimum 2d` and `bare minimum 3d ` as peer dependencies in your `package.json`
> (I guess it's a plugin ?)

Yes, I'd love to, but I couldn't find a way to add custom elements to [`svgElements`](https://github.com/mithi/bare-minimum-2d/blob/753dce99e5661c200275a223c82b7eaedbc79a6e/src/index.js#L17). I'm currently using a hacked version of `bare-minimum-2d`. Is there an API I haven't seen jet?

> If you do, I'll put it a link right before the `demo application` of my READMEs, to make sure everyone who visits the `bare minimum 2d` repo and `bare minimum will know about it!

🙂

**Comment by mithi** [comment]
> Yes, I'd love to, but I couldn't find a way to add custom elements to [`svgElements`](https://github.com/mithi/bare-minimum-2d/blob/753dce99e5661c200275a223c82b7eaedbc79a6e/src/index.js#L17). I'm currently using a hacked version of `bare-minimum-2d`. Is there an API I haven't seen jet?

What do you mean? What happens when you try to add custom elements? What's the error?

**Comment by mithi** [comment]
Forget my first reply. I understand what you mean now... hmmm. 
Let me think about what I can do...

**Comment by mithi** [comment]
I'm thinking what if the API is like this
```js
const trianglePlugin = {
    triangle: (element, transforms) => { /*your implementation here*/ return <polygon {..props}/> }
}

<BareMinimum2d {...{data, container}} plugins=[{trianglePlugin]} /
```
So, basically here's the implementation of the  current API
https://github.com/mithi/bare-minimum-2d/blob/master/src/index.js

And to accomodate for the new API we'll have to change the implemation to something like this
```jsx

/*** SNIP ***/

const elementTypeImplementations = {
    lines: (element, transforms) => <Lines {...element} {...{ transforms }} key={element.id} />,
    polygon: (element, transforms) => <Polygon {...element} {...{ transforms }} key={element.id} />,
    ellipse: (element, transforms) => <Ellipse {...element} {...{ transforms }} key={element.id} />,
    point: (element, transforms) => {
        const { size, color, opacity, id } = element
        return element.x.map((x, i) => (
            <Point
                {...{
                    x,
                    y: element.y[i],
                    size,
                    color,
                    opacity,
                    id,
                    i,
                    transforms,
                }}
                key={`${id}-${i}`}
            />
        ))
    },
}

/*** SNIP ***/

const svgElements = (data, transforms, plugins) => {
    const extendedElementTypeImplementations = plugins.reduce(plugin => {
        return { elementTypeImplementations, ...plugin }
    }, elementTypeImplementations)

    const elements = data.map(element => {
        const implementation = extendedElementTypeImplementations[element.type]
        return implementation(element, transforms)
    })
    return elements.flat()
}

/*** SNIP ***/

class BareMinimum2d extends React.PureComponent {
    /*** SNIP ***/

        return (
            <svg {...svgProps} {...{ viewBox }}>
                <Paper {...{ color, opacity }} />
                {svgElements(data, transforms, plugins)}
            </svg>
        )
    }
}

export default BareMinimum2d

```

Do you think that will work? Would you like to submit a pull request? 
I'll add you as a main contributor in the the README if you do :D

**Comment by mithi** [comment]
@fuddl 
I'm thinking what if the API is like this
```js
const trianglePlugin = {
    triangle: (element, transforms) => { /*your implementation here*/ return <polygon {..props}/> }
}

<BareMinimum2d {...{data, container}} plugins=[{trianglePlugin]} /
```
So, basically here's the implementation of the  current API
https://github.com/mithi/bare-minimum-2d/blob/master/src/index.js

And to accomodate for the new API we'll have to change the implemation to something like this
```jsx

/*** SNIP ***/

const elementTypeImplementations = {
    lines: (element, transforms) => <Lines {...element} {...{ transforms }} key={element.id} />,
    polygon: (element, transforms) => <Polygon {...element} {...{ transforms }} key={element.id} />,
    ellipse: (element, transforms) => <Ellipse {...element} {...{ transforms }} key={element.id} />,
    point: (element, transforms) => {
        const { size, color, opacity, id } = element
        return element.x.map((x, i) => (
            <Point
                {...{
                    x,
                    y: element.y[i],
                    size,
                    color,
                    opacity,
                    id,
                    i,
                    transforms,
                }}
                key={`${id}-${i}`}
            />
        ))
    },
}

/*** SNIP ***/

const svgElements = (data, transforms, plugins) => {
    const extendedElementTypeImplementations = plugins.reduce(plugin => {
        return { elementTypeImplementations, ...plugin }
    }, elementTypeImplementations)

    const elements = data.map(element => {
        const implementation = extendedElementTypeImplementations[element.type]
        return implementation(element, transforms)
    })
    return elements.flat()
}

/*** SNIP ***/

class BareMinimum2d extends React.PureComponent {
    /*** SNIP ***/

        return (
            <svg {...svgProps} {...{ viewBox }}>
                <Paper {...{ color, opacity }} />
                {svgElements(data, transforms, plugins)}
            </svg>
        )
    }
}

export default BareMinimum2d

```

Do you think that will work? Would you like to submit a pull request? 
I'll add you as a main contributor in the the README if you do :D

**Comment by mithi** [comment]
@fuddl 
I'm thinking what if the API is like this
```js
const trianglePlugin = {
    triangle: (element, transforms) => { /*your implementation here*/ return <polygon {..props}/> }
}

<BareMinimum2d {...{data, container}} plugins=[{trianglePlugin]} /
```
So, basically here's the implementation of the  current API
https://github.com/mithi/bare-minimum-2d/blob/master/src/index.js

And to accomodate for the new API we'll have to change the implemation to something like this
```jsx

/*** SNIP ***/

const elementTypeImplementations = {
    lines: (element, transforms) => <Lines {...element} {...{ transforms }} key={element.id} />,
    polygon: (element, transforms) => <Polygon {...element} {...{ transforms }} key={element.id} />,
    ellipse: (element, transforms) => <Ellipse {...element} {...{ transforms }} key={element.id} />,
    point: (element, transforms) => {
        const { size, color, opacity, id } = element
        return element.x.map((x, i) => (
            <Point
                {...{
                    x,
                    y: element.y[i],
                    size,
                    color,
                    opacity,
                    id,
                    i,
                    transforms,
                }}
                key={`${id}-${i}`}
            />
        ))
    },
}

/*** SNIP ***/

const svgElements = (data, transforms, plugins) => {
    const extendedElementTypeImplementations = plugins.reduce(plugin => {
        return { elementTypeImplementations, ...plugin }
    }, elementTypeImplementations)

    const elements = data.map(element => {
        const implementation = extendedElementTypeImplementations[element.type]
        return implementation(element, transforms)
    })
    return elements.flat()
}

/*** SNIP ***/

class BareMinimum2d extends React.PureComponent {
/*** SNIP ***/

  render() {
    const { container, data, plugins } = this.props
    /*** SNIP ***/

    return (
      <svg {...svgProps} {...{ viewBox }}>
        <Paper {...{ color, opacity }} />
        {svgElements(data, transforms, plugins)}
      </svg>
    )
  }
}
```

Do you think that will work? Would you like to submit a pull request? 
I'll add you as a main contributor in the the README if you do :D

**Comment by mithi** [comment]
@fuddl 
I'm thinking what if the API is like this
```js
const trianglePlugin = {
    triangle: (element, transforms) => { /*your implementation here*/ return <polygon {..props}/> }
}

<BareMinimum2d {...{data, container}} plugins=[{trianglePlugin]} /
```
So, basically here's the implementation of the  current API
https://github.com/mithi/bare-minimum-2d/blob/master/src/index.js

And to accomodate for the new API we'll have to change the implemation to something like this
```jsx

/*** SNIP ***/

const elementTypeImplementations = {
    lines: (element, transforms) => <Lines {...element} {...{ transforms }} key={element.id} />,
    polygon: (element, transforms) => <Polygon {...element} {...{ transforms }} key={element.id} />,
    ellipse: (element, transforms) => <Ellipse {...element} {...{ transforms }} key={element.id} />,
    point: (element, transforms) => {
        const { size, color, opacity, id } = element
        return element.x.map((x, i) => (
            <Point
                {...{
                    x,
                    y: element.y[i],
                    size,
                    color,
                    opacity,
                    id,
                    i,
                    transforms,
                }}
                key={`${id}-${i}`}
            />
        ))
    },
}

/*** SNIP ***/

const svgElements = (data, transforms, plugins) => {
    const extendedElementTypeImplementations = plugins.reduce((extended, plugin) => {
        return { extended, ...plugin }
    }, elementTypeImplementations)

    const elements = data.map(element => {
        const implementation = extendedElementTypeImplementations[element.type]
        return implementation(element, transforms)
    })
    return elements.flat()
}

/*** SNIP ***/

class BareMinimum2d extends React.PureComponent {
/*** SNIP ***/

  render() {
    const { container, data, plugins } = this.props
    /*** SNIP ***/

    return (
      <svg {...svgProps} {...{ viewBox }}>
        <Paper {...{ color, opacity }} />
        {svgElements(data, transforms, plugins)}
      </svg>
    )
  }
}
```

Do you think that will work? Would you like to submit a pull request? 
I'll add you as a main contributor in the the README if you do :D

**Comment by mithi** [comment]
@fuddl 
I'm thinking what if the API is like this
```js
const trianglePlugin = {
    triangle: (element, transforms) => { /*your implementation here*/ return <polygon {..props}/> }
}

<BareMinimum2d {...{ data, container }} plugins={[trianglePlugin]} /
```
So, basically here's the implementation of the  current API
https://github.com/mithi/bare-minimum-2d/blob/master/src/index.js

And to accomodate for the new API we'll have to change the implemation to something like this
```jsx

/*** SNIP ***/

const elementTypeImplementations = {
    lines: (element, transforms) => <Lines {...element} {...{ transforms }} key={element.id} />,
    polygon: (element, transforms) => <Polygon {...element} {...{ transforms }} key={element.id} />,
    ellipse: (element, transforms) => <Ellipse {...element} {...{ transforms }} key={element.id} />,
    point: (element, transforms) => {
        const { size, color, opacity, id } = element
        return element.x.map((x, i) => (
            <Point
                {...{
                    x,
                    y: element.y[i],
                    size,
                    color,
                    opacity,
                    id,
                    i,
                    transforms,
                }}
                key={`${id}-${i}`}
            />
        ))
    },
}

/*** SNIP ***/

const svgElements = (data, transforms, plugins) => {
    const extendedElementTypeImplementations = plugins.reduce((extended, plugin) => {
        return { extended, ...plugin }
    }, elementTypeImplementations)

    const elements = data.map(element => {
        const implementation = extendedElementTypeImplementations[element.type]
        return implementation(element, transforms)
    })
    return elements.flat()
}

/*** SNIP ***/

class BareMinimum2d extends React.PureComponent {
/*** SNIP ***/

  render() {
    const { container, data, plugins } = this.props
    /*** SNIP ***/

    return (
      <svg {...svgProps} {...{ viewBox }}>
        <Paper {...{ color, opacity }} />
        {svgElements(data, transforms, plugins)}
      </svg>
    )
  }
}
```

Do you think that will work? Would you like to submit a pull request? 
I'll add you as a main contributor in the the README if you do :D 
Let me know your thoughts...

**Comment by mithi** [comment]
> It looks good to me. I tried to add an example [in this fork](https://github.com/fuddl/bare-minimum-2d/commit/0cfd83f5c666126c3612ce28a8532c8955661d19)
> 
> How do I build the examples?


In one terminal tab
```
npm install && npm run start
```

in another tab
```
cd example && npm install && npm run start
```

Let me know if it works!

**Comment by fuddl** [comment]
On the second step I'm getting this enormous error:

```
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-jest": "^24.9.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-jest was detected higher up in the tree:

  /bare-minimum-2d/node_modules/babel-jest (version: 26.3.0) 

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "babel-jest" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if /bare-minimum-2d/node_modules/babel-jest is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls babel-jest in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed babel-jest.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bare-minimum-2d-example@0.0.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bare-minimum-2d-example@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
I will look into it later

**Comment by mithi** [comment]
@fuddl 

I think I encountered that when I was deploying to netlify.

I think I had to remove  node modules in the root directory after compiling
ie `npm install` && `rm -rf node_modules` && `cd example` && `npm install` && `npm run start`

I'll clone your fork tomorrow and see what I can do...

**Comment by fuddl** [comment]
manually deleting the root node_modules helped

**Comment by fuddl** [comment]
@mithi I hope you don't mind, that I am using `demo3` to demonstrate the plugin feature!?

I think I'm almost there. Can you tell me why my triangle plugin is misplaced?

![displaced triangle](https://user-images.githubusercontent.com/842548/111674299-28ce4280-881c-11eb-8582-56415ecc71dc.png)

**Comment by fuddl** [comment]
@mithi should I open a PR?

![triangle on a wheel](https://user-images.githubusercontent.com/842548/111680995-186d9600-8823-11eb-9e01-8a7f53a19b92.png)

**Comment by mithi** [comment]
> @mithi should I open a PR?
> 
> ![triangle on a wheel](https://user-images.githubusercontent.com/842548/111680995-186d9600-8823-11eb-9e01-8a7f53a19b92.png)

You confident with your PR? Go ahead? 😀

**Comment by fuddl** [comment]
> @fuddl
> My recommendation is that you write a package given this functionality (if you feel inclined)
> and just list `bare minimum 2d` and `bare minimum 3d ` as peer dependencies in your `package.json`

@mithi as you suggested, I wrote [bare-minimum-text-marker](https://github.com/fuddl/bare-minimum-text-marker/). Feedback is appreciated. 😀

**Comment by mithi** [comment]
Really cool! I'll check it out in greater detail tomorrow  😀

**Comment by mithi** [comment]
> @mithi as you suggested, I wrote [bare-minimum-text-marker](https://github.com/fuddl/bare-minimum-text-marker/). Feedback is appreciated. 😀

Hey I checked this out! Really cool!
My suggestions:
1. Deploy your example app to github pages
  - https://dev.to/yuribenjamin/how-to-deploy-react-app-in-github-pages-2a1f
2. Publish the plugin to NPM here are some beginner guides to help you: 
    - https://zellwk.com/blog/publish-to-npm/
    - https://dev.to/therealdanvega/creating-your-first-npm-package-2ehf

What do you think? 😀

**Comment by fuddl** [comment]
>     1. Deploy your example app to github pages
> 
> 
>     * https://dev.to/yuribenjamin/how-to-deploy-react-app-in-github-pages-2a1f

Ah, thanks. I was wondering how to do that.

>     2. Publish the plugin to NPM here are some beginner guides to help you:

Its already [on npm](https://www.npmjs.com/package/bare-minimum-text-marker).

**Comment by mithi** [comment]
> Its already [on npm](https://www.npmjs.com/package/bare-minimum-text-marker).

Awesome! I'll link to your repo in the readme once you deploy the example on github pages :D

**Comment by fuddl** [comment]
@mithi [here we go](https://fuddl.github.io/bare-minimum-text-marker/).

Please post future suggestions [as issue](https://github.com/fuddl/bare-minimum-text-marker/issues)
